name: Export and Unpack Solution

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Solution unique name'
        required: true
        default: 'Sims'

jobs:
  export-unpack:
    runs-on: windows-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform tools
        uses: microsoft/powerplatform-actions/actions-install@v1.9.2
        with:
          add-tools-to-path: true

      - name: Publish customizations
        uses: microsoft/powerplatform-actions/publish-solution@v1.9.2
        with:
          environment-url: ${{ secrets.POWERPLATFORM_DEV_URL }}
          app-id: ${{ secrets.POWERPLATFORM_CLIENT_ID }}
          client-secret: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.POWERPLATFORM_TENANT_ID }}

      - name: Export solution (unmanaged)
        uses: microsoft/powerplatform-actions/export-solution@v1.9.2
        with:
          environment-url: ${{ secrets.POWERPLATFORM_DEV_URL }}
          app-id: ${{ secrets.POWERPLATFORM_CLIENT_ID }}
          client-secret: ${{ secrets.POWERPLATFORM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.POWERPLATFORM_TENANT_ID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: out/exported/${{ github.event.inputs.solution_name }}.zip

      - name: Auth for Checker
        run: |
          pac auth create --url "${{ secrets.POWERPLATFORM_DEV_URL }}" --applicationId "${{ secrets.POWERPLATFORM_CLIENT_ID }}" --clientSecret "${{ secrets.POWERPLATFORM_CLIENT_SECRET }}" --tenant "${{ secrets.POWERPLATFORM_TENANT_ID }}"
        shell: pwsh

      - name: Run Solution Checker
        continue-on-error: true
        run: |
